optim:
  iterations: 1200
  lr: 0.01
  include_predcp: True
  gamma: ${net.optim.gamma}
  scaling_fct: 0.5
  tv_samples: 1000
priors:
  lengthscale_init: 0.1
  variance_init: 1
  include_normal_priors: True
impl:
  use_fwAD_for_jvp: True
  vec_batch_size: 2
  log_grad_cg_residual: True
