optim:
  iterations: 1200
  lr: 0.01
  include_predcp: True
  gamma: ${net.optim.gamma}
  scl_fct_gamma: None
  scaling_fct: 2
  tv_samples: 1000
  use_fwAD_for_jvp: True
priors:
  lengthscale_init: 0.1
  variance_init: 1
  include_normal_priors: True
