optim:
  iterations: 1200
  lr: 0.01
  include_predcp: True
  gamma: ${net.optim.gamma}
  scl_fct_gamma: None
  scaling_fct: 2
priors:
  lengthscale_init: 0.1
linearized_weights:
  lr: 5e-4
  wd: 1e-8
  iterations: 15000
