defaults:
  - data: kmnist
  - trafo: simple_ray_trafo
  - net: unet
  - lin_params: lin_params
  - mrglik: mrglik
  - density: density
  - trn: trainer
seed: 1
linearize_weights: False
num_images: 1
use_double: False
hydra:
  run:
    dir: outputs/${now:%Y-%m-%dT%H:%M:%S.%fZ}
ignore_gpytorch_numerical_warnings: True
